name: Tibco Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


        

       

    - name: Build and Package BW6 Application
      run: |
        cd src/sm.baseSchemas
        mvn clean package -P mavenize
      env:
        MAVEN_OPTS: '-Dmaven.repo.local=./.m2/repository'
        


      


    - name: Build and push images
      run : | 

          sudo docker build -t smbase:smbase -f /home/ubuntu/actions-runner/_work/sm.baseSchema/sm.baseSchema/src/sm.baseSchemas/Dockerfile .

    -  name: Login to Docker Hub
       run : |
           sudo docker tag smbase nil579/smbase:smbase
           sudo docker login -u nil579 -p Docker579
           sudo docker push nil579/smbase:smbase
