name: Tibco Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


        

       

    - name: Build and Package BW6 Application
      run: |
        cd src/sm.baseSchemas
        mvn clean package -P mavenize
      env:
        MAVEN_OPTS: '-Dmaven.repo.local=./.m2/repository'
        


      


    - name: Build and push images
      run : | 

          sudo docker build -t smbase:latest -f /home/ubuntu/actions-runner/_work/sm.baseSchema/sm.baseSchema/src/sm.baseSchemas/Dockerfile .

    - name: Tag Docker image
      run: |
          docker tag smbase:latest smbase/smbase:latest
          docker login -u nil579 -p Docker@579
          


    - name: Push Docker image to Docker Hub
      run: docker push nil579/smbase
            

