name: Tibco Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK and Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        
    - name: Print Current Directory
      run : ls -la /home/runner/work/sm.baseSchema/sm.baseSchema/src/sm.baseSchemas/target
       
      

    -  name: Set up QEMU
       uses: docker/setup-qemu-action@v3
      
    -  name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
      
    -  name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
          username: nil579
          password: Docker@579
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          push: true
          tags: nil579/sm.baseschema:latest
         
    - name: Build and Package BW6 Application
      run: |
        cd src/sm.baseSchemas
        mvn clean package -P mavenize
      env:
        MAVEN_OPTS: '-Dmaven.repo.local=./.m2/repository'

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: /home/runner/work/sm.baseSchema/sm.baseSchema/src/sm.baseSchemas/target/Dockerfile
        push: true
        tags: nil579/sm.baseschema:latest
        
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Package and Publish EAR Artifact
      run: |
        cd src/sm.baseSchemas/target
        echo "BW6 Application EAR file successfully built and packaged."
      env:
        MAVEN_OPTS: '-Dmaven.repo.local=./.m2/repository'
