
FROM nginx

# (Optional) Set any custom configurations or copy custom files
# For example, you can copy custom configuration files from your host machine to the container
# COPY nginx.conf /etc/nginx/nginx.conf

# (Optional) Expose any ports required by the application
# By default, Nginx listens on port 80, so it's not necessary to use the EXPOSE instruction unless you want to expose other ports
EXPOSE 80

# (Optional) Define any environment variables if needed
# ENV ENV_VARIABLE value

# (Optional) Define the default command to run when the container starts
# By default, Nginx starts automatically when the container starts
# CMD ["nginx", "-g", "daemon off;"]
