FROM bwce/runtime:2.5.5

WORKDIR /app

COPY /home/ubuntu/actions-runner/_work/sm.baseSchema/sm.baseSchema/src/sm.baseSchemas/target/sm.baseSchemas-1.2-SNAPSHOT.jar /app

EXPOSE 8080

# Define the command to run the application when the container starts
# For example, if the JAR file is executable and runs on its own, you can use:
# CMD ["java", "-jar", "sm.baseSchemas-1.2-SNAPSHOT.jar"]
